### ISSUE TITLE
Unsafe parameter passing in dbif.gencur.createdb

### ISSUE THREAD

**Issue by ftsamis** [gisab/gmp#1]
When the gmp database does not exist, and createdb is called, it runs a mysql shell command with unsafe passing of arguments (not escaped). That is dangerous and will cause issues even in cases where the password contains special shell symbols such as `$`.

```
cli='mysql --user=%s --password=%s --host=%s --port=%s --database=%s < %s' 
cli=cli % (cuser, cpwd, chost, cport, cschema, ifile)
```

**Comment by gisab** [comment]
Hi Fotis. Thanks for the comment.
I just fix it.

**Comment by ftsamis** [comment]
Hello, checking your commit I believe you'll need to use single quotes instead of double, as those will still evaluate shell variables (causing problems when the $ symbol is found).

You can confirm that with e.g. `echo "$PWD"` vs `echo '$PWD'`.

Thanks for the quick response.

**Comment by gisab** [comment]
You are right; please check it again.
